Sprint 3
Kuart/middle.messenger.praktikum.yandex pull request #1
Opened 2021-08-10 08:22 UTC by Kuart

2021-08-12 11:25 UTC, nickchamel requested changes
Привет. Я помню, что у тебя сильная работа, но очень сложно проверять с нуля...
1. Почему ты удалил пулл-реквесты? В частности последний открытый. Прошло 12 дней с его момента - я не помню что там было.
2. Почему у тебя в одном пулл-реквесте все 3 спринта вместе?
Ты мог создать ветку из этого коммита
![image](https://user-images.githubusercontent.com/28347933/129186818-4a4c0385-72f3-41c7-b42c-541d4d253a96.png)
а на другую ветку перенести все последующие коммиты и все было бы хорошо.
Замечания по заданиям (необходимо доработать):
![image](https://user-images.githubusercontent.com/28347933/129187069-d7bc18ef-3854-4f7e-b2b9-99fca5b976ab.png)
После перезагрузки страниц - они не работают.
![image](https://user-images.githubusercontent.com/28347933/129187331-ab95c057-64a8-49ba-9660-1f632d41a852.png)
Сообщения в чатах не подгружаются, при отправке не появляются
![image](https://user-images.githubusercontent.com/28347933/129187719-93d127fc-1152-483e-9b96-5f90f8654115.png)
Аватар не грузится
![image](https://user-images.githubusercontent.com/28347933/129187778-447f6d1d-c5ee-43c5-989f-1e588a5ecf1a.png)
При успешном апдейте профиля, обновленные данные не отображаются в UI.
Так же, на страницах логина/регистрации не работает валидация на блюре (по заданию вроде должна быть)
Плюс: 
чекни dependencies в package.json. Сомневаюсь, что они у тебя используются
![image](https://user-images.githubusercontent.com/28347933/129188997-27203026-59c8-4747-ae31-a74633b71e44.png)

2021-08-12 12:54 UTC, Kuart commented
1 и 2 т.к. после выхода из академа мне написали что надо удалить старый репозиторий, создать новый и перепривязать GH

2021-08-14 18:30 UTC, nickchamel approved these changes
Привет. Небольшой нюанс еще заметил только - отображаемое в чатах имя, при редактировании в профиле, меняется только после перезагрузки страницы.
В остальном все отлично, Молодец! Работу принял, удачи в дальнейшем.

2021-08-14 18:30 UTC, nickchamel commented on src/modules/Messanger/Header/Menu/Profile/profile-edit.controller.ts
> +    const user = await userAPI.changeAvatar(newForm);
Если `userAPI.changeAvatar` выбрасывает исключение (reject), то здесь нужен try/catch. В остальных таких местах так же

2021-08-14 18:53 UTC, merged